function setPID{
	PARAMETER err.
	PARAMETER prop IS 0.2.
	DECLARE LOCAL Kp TO prop.
	DECLARE LOCAL Ki TO prop*0.5.
	DECLARE LOCAL Kd TO prop*0.0125.
	DECLARE LOCAL PIDL TO PIDLOOP(Kp, Kp, Kd).
	SET PIDL:SETPOINT TO err.
	return PIDL.
}